# Generated by Django 2.2.4 on 2019-10-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20191003_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='paid',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
