# Generated by Django 2.2.4 on 2019-10-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20191003_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
