# Generated by Django 2.2.4 on 2019-11-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='in_cart',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
