# Generated by Django 2.2.4 on 2019-09-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20190928_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='percent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
