# Generated by Django 2.2.4 on 2019-09-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20190928_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
