# Generated by Django 2.2.4 on 2019-10-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20190928_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
