# Generated by Django 2.2.4 on 2019-11-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0005_auto_20191029_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='description',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='title',
        ),
    ]
