# Generated by Django 2.2.4 on 2019-09-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.TextField(default=''),
        ),
    ]
