# Generated by Django 2.2.4 on 2019-09-24 08:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190924_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
    ]
