# Generated by Django 2.2.4 on 2019-09-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190924_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
