# Generated by Django 2.2.4 on 2019-09-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
