# Generated by Django 2.2.4 on 2019-09-27 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='img',
            new_name='image',
        ),
    ]
