# Generated by Django 2.2.4 on 2019-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20190928_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
