# Generated by Django 2.2.4 on 2019-10-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purchased_at',
            new_name='ordered_at',
        ),
    ]
