# Generated by Django 2.2.4 on 2019-10-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191013_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
