# Generated by Django 2.2.4 on 2019-10-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('order', '0005_order_bill_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receiver_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='address.Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_address', to='address.Address'),
        ),
    ]
