# Generated by Django 2.2.4 on 2019-10-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191030_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'waiting'), ('pending', 'pending'), ('shipping', 'shipping'), ('success', 'success'), ('canceled', 'canceled')], default='waiting', max_length=20, null=True),
        ),
    ]
