# Generated by Django 2.2.4 on 2019-11-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191031_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
