# Generated by Django 2.2.4 on 2019-11-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191107_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='receipt_link',
            new_name='receipt_url',
        ),
    ]
