# Generated by Django 2.2.4 on 2019-09-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
    ]
