# Generated by Django 2.2.4 on 2019-09-23 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190923_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='postcode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
