# Generated by Django 2.2.4 on 2019-09-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190923_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fullname',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
