# Generated by Django 2.2.4 on 2019-10-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_member_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='postcode',
        ),
    ]
