# Generated by Django 2.2.4 on 2019-10-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_member_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
