# Generated by Django 2.2.4 on 2019-10-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
