# Generated by Django 2.2.4 on 2019-09-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_auto_20190928_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
